### ISSUE TITLE
Adapt the website to make it mobile friendly

### ISSUE THREAD

**Issue by PulkitMishra** [IIITKalyaniFOSC/iiitkalyanifosc.github.io#9]
The current website runs smoothly on desktop/laptop. However, it is not designed to work on mobile phones. Make the necessary changes in the already existing mobile.css file.

**Comment by zeus0789** [comment]
@PulkitMishra really wanted to use bootstrap's mobile friendly classes. :-(

**Comment by anubhavp28** [comment]
@zeus0789 @PulkitMishra If everybody wants to include `bootstrap.js`, it is fine! But I would still say in my eyes there is no need for `bootstrap.js`. Infact going without `bootstrap.js` is better because it really provides a opportunity to understand how to create mobile friendly website. __Responsive Web Apps__.

**Comment by PulkitMishra** [comment]
I agree @anubhavp28 . There's no need of bootstrap here @zeus0789 . Media queries and dropdown (or popout ?) layout would do just fine.

**Comment by zeus0789** [comment]
@PulkitMishra @anubhavp28 almost done

**Comment by AnkurKonar** [comment]
@zeus0789 no changes seen as such. And make the width height and spacings  in %. I guess that ought to do it without bootstrap.

**Comment by Satyam-TG** [comment]
I have adapted the website for better viewing on mobiles and created a pull request for the same. See the pull request to check it out.
